#! /bin/bash
### BEGIN INIT INFO
# Provides:          theapp
# Required-Start:    
# Required-Stop:
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: 
# Description:       The gunicorn process
#                    from nginx
#
### END INIT INFO
#
#
APPNAME=qlines
#USER=youruser
#PATH=/sbin:/bin:/usr/sbin:/usr/bin #/bin:/usr/bin:/sbin:/usr/sbin
#ACTIVATE=/home/www/project/env/bin/activate

APP_PATH="/opt/qlines_app"
DAEMON="/opt/qlines_venv/bin/gunicorn"  # Adjust this to the path of your gunicorn executable
GUNICORN_ARGS="-w 4 qlines:app --chdir $APP_PATH"

#APPMODULE=yourproject.wsgi:application
#DAEMON=gunicorn
BIND="0.0.0.0:80"
PIDFILE=/var/run/gunicorn.pid
LOGFILE=/var/log/gunicorn.log
WORKERS=2

. /lib/lsb/init-functions

if [ -e "/etc/default/$APPNAME" ]
then
    . /etc/default/$APPNAME
fi


case "$1" in
  start)
        log_daemon_msg "Starting gunicorn for the app" "$APPNAME"
        #source $ACTIVATE
        $DAEMON --daemon --bind=$BIND --pid=$PIDFILE --workers=$WORKERS --log-file=$LOGFILE $GUNICORN_ARGS
        log_end_msg $?
    ;;
  stop)
        log_daemon_msg "Starting gunicorn for the app" "$APPNAME"
        killproc -p $PIDFILE $DAEMON
        log_end_msg $?
    ;;
  force-reload|restart)
    $0 stop
    $0 start
    ;;
  status)
    status_of_proc -p $PIDFILE $DAEMON && exit 0 || exit $?
    ;;
  *)
    echo "Usage: /etc/init.d/$APPNAME {start|stop|restart|force-reload|status}"
    exit 1
    ;;
esac

exit 0
