#!/bin/sh
### BEGIN INIT INFO
# Provides:          gunicorn-qlines
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Gunicorn init script for qlines app
# Description:       Gunicorn init script for running the qlines app with Gunicorn
### END INIT INFO

PATH=/sbin:/bin:/usr/sbin:/usr/bin
DESC="Gunicorn Qlines App"
NAME=gunicorn-qlines
APP_PATH="/opt/qlines_app"
GUNICORN_EXEC="/usr/local/bin/gunicorn"  # Adjust this to the path of your gunicorn executable
GUNICORN_ARGS="--worker-class eventlet -w 1 qlines:app --bind 0.0.0.0:5000 --chdir $APP_PATH"
PIDFILE="/var/run/$NAME.pid"
#USER="your_username"  # Adjust this to the user you want to run Gunicorn as
#GROUP="your_groupname"  # Adjust this to the group you want to run Gunicorn as

set -e

. /lib/lsb/init-functions

start() {
    echo "Starting $DESC"
    start-stop-daemon --start --background --pidfile "$PIDFILE" --make-pidfile --exec "$GUNICORN_EXEC" -- $GUNICORN_ARGS
    log_end_msg $?
}

stop() {
    echo "Stopping $DESC"
    start-stop-daemon --stop --pidfile "$PIDFILE" --retry 10
    log_end_msg $?
    rm -f "$PIDFILE"
}

case "$1" in
    start)
        start
        ;;
    stop)
        stop
        ;;
    restart|reload)
        stop
        sleep 1
        start
        ;;
    *)
        echo "Usage: $0 {start|stop|restart}"
        exit 1
        ;;
esac

exit 0

